version: '3.8'

services:
  prefect-db:
    image: postgres:13
    environment:
      POSTGRES_USER: prefect
      POSTGRES_PASSWORD: prefect
      POSTGRES_DB: prefect
    volumes:
      - prefect_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prefect"]
      interval: 5s
      retries: 5

  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    ports:
      - "5001:5000"
    volumes:
      - mlflow_data:/mlruns
    command: >
      mlflow server 
      --host 0.0.0.0
      --port 5000

  prefect-server:
    build:
      context: .
      dockerfile: prefect.Dockerfile
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      prefect-db:
        condition: service_healthy
    environment:
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://prefect:prefect@prefect-db:5432/prefect
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
    volumes:
      - .:/app
    working_dir: /app
    command: prefect server start
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect-init:
    build:
      context: .
      dockerfile: prefect.Dockerfile
    restart: on-failure:3
    depends_on:
      prefect-server:
        condition: service_healthy
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - GITHUB_TOKEN=${GH_TOKEN}
      - GITHUB_REPOSITORY=${GITHUB_REPOSITORY}
      - GITHUB_BRANCH=${GITHUB_BRANCH}
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        python /app/init_blocks/init.py &&
        sleep 5 &&
        if ! prefect work-pool inspect ml-pool > /dev/null 2>&1; then
          echo 'Creating work pool ml-pool'
          prefect work-pool create ml-pool --type process
        else
          echo 'Work pool ml-pool already exists'
        fi &&
        echo 'Creating deployment for data_pipeline flow' &&
        sleep 5 &&
        python /app/deployments/create_deployment.py
      "

  prefect-worker:
    build:
      context: .
      dockerfile: prefect.Dockerfile
    depends_on:
      prefect-server:
        condition: service_healthy
      prefect-init:
        condition: service_started
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    volumes:
      - .:/app
    working_dir: /app
    command: prefect worker start -p ml-pool

volumes:
  prefect_postgres_data:
  mlflow_data: